-- local ft_lsp_group = vim.api.nvim_create_augroup('ft_lsp_group', { clear = true })
--
-- vim.api.nvim_create_autocmd({ 'BufReadPost', 'BufNewFile' }, {
--   pattern = { 'docker-compose.yaml', 'compose.yaml' },
--   group = ft_lsp_group,
--   desc = 'Fix the issue where the LSP does not start with docker-compose.',
--   callback = function()
--     vim.opt.filetype = 'yaml.docker-compose'
--   end,
-- })

-- Use this if you want it to automatically show all diagnostics on the
-- current line in a floating window. Personally, I find this a bit
-- distracting and prefer to manually trigger it (see below). The
-- CursorHold event happens when after `updatetime` milliseconds. The
-- default is 4000 which is much too long
-- vim.cmd 'autocmd CursorHold * lua vim.lsp.diagnostic.show_line_diagnostics()'
-- vim.o.updatetime = 300
